version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: na_ponimanii_app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./env:/app/env
      - ./config:/app/config
    environment:
      - API_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
      - STATSD_HOST=statsd-exporter
      - STATSD_PORT=9125
      - DB_PATH=/app/data/data.db
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    command: >
      bash -c "
        mkdir -p /app/data &&
        /app/venv/bin/python src/server/app.py &
        /app/venv/bin/python src/bot/telegram_bot.py
      "
    depends_on:
      - statsd-exporter

  statsd-exporter:
    image: prom/statsd-exporter:latest
    container_name: na_ponimanii_statsd_exporter
    command: --statsd.mapping-config=/etc/statsd-exporter/statsd_mapping.yml
    volumes:
      - ./config/statsd_mapping.yml:/etc/statsd-exporter/statsd_mapping.yml
    ports:
      - "9125:9125/udp"
      - "9102:9102"      # Prometheus metrics exposure
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: na_ponimanii_prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    depends_on:
      - statsd-exporter

volumes:
  prometheus_data: