version: '3.8'

services:
  app:
    build: .
    container_name: na_ponimanii_app
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./env:/app/env
    environment:
      - API_HOST=0.0.0.0
    ports:
      - "8000:8000"
    restart: unless-stopped
    command: >
      bash -c "
        mkdir -p /app/data &&
        python src/server/app.py &
        python src/bot/telegram_bot.py
      "